server:
  port: 8085
spring:
  #格式化日期时间
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #读取图片配置
  resources:
    static-locations: classpath:/static/,classpath:/public/,file:${myconfig.uploadpath}
  #数据源配置
  datasource:
    url: jdbc:oracle:thin:@114.116.55.14:1521:ctmsdb
    username: ctmsyd
    password: Ctms123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    # 初始化大小，最小，最大
    maxActive: 20
    initialSize: 1
    minIdle: 1
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #filters: stat
  messages:
    basename: i18n/messages
  #mybaits-plus
mybatis-plus:
  config-location: classpath:mybatis/config/mybatis.cfg.xml # mybatis配置文件所在路径
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.forceclouds.ctms.dao.entity
  global-config:
    db-config:
      id-type: ID_WORKER_STR
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#自定义配置
myconfig:
  #上传文件路径
  uploadpath: D:/uploads/test/
  #客户端端口
  clientPort: 8096



